apiVersion: infrastructure.omni.siderolabs.io/v1alpha1
kind: MachineClass
metadata:
  name: incus-single-node
spec:
  type: auto-provision
  provider: incus
  config:
    type: virtual-machine
    cpu: 4
    memory: 8192
    diskSize: 40
    imageAlias: talos
    additionalDisks:
      - pool: default
        size: 100GiB
    profiles:
      - default
